[book]
authors = ["chai2010"]
description = ""
language = "zh"
src = "."
title = "Linux C"

[output.html]
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/mazezen/linuxcmanual"
