[book]
authors = ["mazezen"]
description = "这是一本名為“Linux C 函数參考”的在线函数参考手册"
language = "zh"
src = "."
title = "Linux C"

[output.html]
git-repository-icon = "fa-github"
git-repository-url = "https://github.com/mazezen/linuxcmanual"
